[versions]
# Kotlin
kotlin = "1.6.10"
coroutines = "1.6.0"
# Dependency Injection
koin = "3.2.0-beta-1"
# Testing
kotest = "5.2.1"
# Gradle
android_gradle = "7.1.2"
# Compose
compose = "1.2.0-alpha03"
compose_compiler = "1.1.0-rc02"
accompanist = "0.22.0-rc"
# Gradle Version plugin
gradle_versions = "0.42.0"
# Static analyze code
ktlint = "0.45.1"
ktlint_jlleitschuh = "10.2.1"
detekt = "1.19.0"
spotless = "6.3.0"
arrow_analysis = "0.42.0"

[libraries]
# Kotlin
kotlin_stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin_ext = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin_reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
serialization_json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"
coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
# AndroidX
activity_compose = "androidx.activity:activity-compose:1.4.0"
core_ktx = "androidx.core:core-ktx:1.7.0"
appcompat = "androidx.appcompat:appcompat:1.4.1"
material = "com.google.android.material:material:1.6.0-alpha01"
lifecycle_ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
# Compose
compose_compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose_compiler" }
compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose_material = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose_tooling_preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose_foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose_runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
navigation_compose = "androidx.navigation:navigation-compose:2.5.0-alpha02"
# Store
datastore_preferences = "androidx.datastore:datastore-preferences:1.0.0"
# Loggers
timber = "com.jakewharton.timber:timber:5.0.1"
prettyLogger = "com.orhanobut:logger:2.2.0"
# Network
retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
serialization_converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
okhttp = "com.squareup.okhttp3:okhttp:4.9.2"
okhttp_bom = "com.squareup.okhttp3:okhttp-bom:5.0.0-alpha.4"
okhttp_bom_core = "com.squareup.okhttp3:okhttp"
okhttp_bom_interceptor = "com.squareup.okhttp3:logging-interceptor"
# Dependency Injection
koin_core = { module = "io.insert-koin:koin-core", version.ref = "koin"}
koin_android = { module = "io.insert-koin:koin-android", version.ref = "koin"}
koin_compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin"}
koin_test = { module = "io.insert-koin:koin-test", version.ref = "koin"}
# Testing - assertation framework
kotest_assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest"}
kotest_junit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest"}
# Accompanist
pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist"}
pager_indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist"}
insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist"}
navigation_material = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist"}
navigation_animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist"}
system_ui_controller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist"}
# Other
sandwich ="com.github.skydoves:sandwich:1.2.3"
mvi_orbit = "org.orbit-mvi:orbit-viewmodel:4.3.2"
coil = "io.coil-kt:coil-compose:1.4.0"
klock = "com.soywiz.korlibs.klock:klock:2.7.0"
